openapi:
  title: api_leads API
  version: 1.0.0
  description: API gerada automaticamente pelo Vaden.
  enable: true

postgres:
  host: localhost
  database: banco-portal
  port: 5433
  username: postgres
  password: senha
  ssl: disable
server:
  port: 8080
  host: localhost

env:
  base_url: http://localhost
  mode: debug